### PR TITLE
fix: cargo build/install -p resolves target to shader crate

### LINKED ISSUE #121: `cargo-gpu` can't find `Cargo.toml` from a package specified with `cargo build -p {package}`
This is because internally I treated `-p` as a synonym for `--shader-crate`, but the latter is a _path_ while the former specifies the **name of a package**. 

These actually have to be distinct parameters with separate handling. `-p` needs to do a lookup in the workspace for the package to resolve the path to the crate.

### PR DESCRIPTION
**Pull request by schell**
These changes fix #121 by separating `--package/-p` from `--shader-crate` args and performing a lookup using `cargo_metadata` to resolve the package name to the shader crate path.

Fixes #121.

### CODE REVIEW

**Comment by schell** [comment]
@tombh it looks like maybe the tests are failing on an old dependency - is this another case where we need to run `cargo update` or similar?

**Comment by tombh** [comment]
Here's the error, it's the same for both the 0.8.0 and 0.9.0 job failures:
```
error: package `indexmap v2.12.0` cannot be built because it requires rustc 1.82 or newer, while the currently active rustc version is 1.71.0-nightly
Either upgrade to rustc 1.82 or newer, or use
cargo update -p indexmap@2.12.0 --precise ver
```

But I notice that our lockfile has:
```yaml
[[package]]
name = "indexmap"
version = "2.6.0"
```

So I can't remember why those old builds might be skipping the lockfile 🤔

**Comment by Firestar99** [comment]
see https://github.com/Rust-GPU/cargo-gpu/issues/123

File: crates/cargo-gpu/src/metadata.rs [hunk 1]
```diff
@@ -9,6 +10,28 @@ use serde_json::Value;
 pub struct Metadata;
 
 impl Metadata {
+    /// Resolve a package name to a crate directory.
+    pub fn resolve_package_to_shader_crate(package: &str) -> anyhow::Result<std::path::PathBuf> {
+        log::debug!("resolving package '{package}' to shader crate");
+        let metadata = MetadataCommand::new().exec()?;
```
Comment (Firestar99) [inline crates/cargo-gpu/src/metadata.rs]: `MetadataCommand::new().exec()` runs the `cargo metadata` and parses it's json output *every time it is called*, it is not cached by `cargo_metadata` itself. We should be able to reuse the `Metadata` to resolve the `spirv-std` version as well.
